branches:
  only:
    - master

services:
  - docker

script:
  - make build || exit 1

after_success:
  - >
    [ "${TRAVIS_BRANCH}" == "master" ] &&
      (docker login --username $DOCKER_USER --password $DOCKER_PASS; \
      docker push ippart/backend)

notifications:
  webhooks:
    urls:
      - http://new.ippart.com/webhook
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
